const fs = require('fs');
const os = require('os');
const path = require('path');

jest.mock('readline', () => ({
  createInterface: jest.fn(),
}));

jest.mock('../lib/ai-complete.cjs', () => ({
  callLLM: jest.fn(),
  getAvailableProvider: jest.fn(),
}));

const readline = require('readline');
const { callLLM, getAvailableProvider } = require('../lib/ai-complete.cjs');
const {
  interactiveCreateRuleset,
  runRulesetWizard,
  createRulesetFromMode,
  createFallbackRuleset,
  resolveInputFiles,
  summarizeFiles,
  discoverRulesetCandidates,
} = require('../lib/ruleset-builder.cjs');

describe('ruleset builder helpers', () => {
  let tempDir;
  let answers;
  let close;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'grabby-ruleset-'));
    fs.mkdirSync(path.join(tempDir, 'docs'), { recursive: true });
    fs.writeFileSync(path.join(tempDir, 'README.md'), '# Hello\n', 'utf8');
    fs.writeFileSync(path.join(tempDir, 'docs', 'guide.md'), 'Guide content', 'utf8');
    fs.writeFileSync(path.join(tempDir, 'docs', 'image.png'), 'not-text', 'utf8');
    close = jest.fn();
    answers = [];
    readline.createInterface.mockImplementation(() => ({
      question: (_prompt, callback) => callback(answers.shift() || ''),
      close,
    }));
    callLLM.mockReset();
    getAvailableProvider.mockReset();
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('resolves files and ignores non-text files', () => {
    const files = resolveInputFiles(tempDir, ['README.md', 'docs']);
    const rel = files.map((f) => path.relative(tempDir, f).replace(/\\/g, '/')).sort();
    expect(rel).toEqual(['README.md', 'docs/guide.md']);
  });

  it('summarizes file snippets with file markers', () => {
    const files = resolveInputFiles(tempDir, ['README.md']);
    const summary = summarizeFiles(tempDir, files);
    expect(summary).toContain('## File: README.md');
    expect(summary).toContain('# Hello');
  });

  it('clips long summaries and respects the maxChars budget', () => {
    fs.writeFileSync(path.join(tempDir, 'docs', 'long.md'), 'a'.repeat(2600), 'utf8');
    const files = resolveInputFiles(tempDir, ['docs']);
    const summary = summarizeFiles(tempDir, files, 40);
    expect(summary).toContain('## File: docs/guide.md');
    expect(summary).not.toContain('## File: docs/long.md');

    const longOnly = summarizeFiles(tempDir, [path.join(tempDir, 'docs', 'long.md')], 5000);
    expect(longOnly).toContain('...');
  });

  it('builds deterministic fallback ruleset content', () => {
    const content = createFallbackRuleset({
      title: 'Team Rules',
      goal: 'Keep pull requests scoped',
      references: ['README.md'],
      mode: 'create-local',
    });
    expect(content).toContain('# RULESET: Team Rules');
    expect(content).toContain('- Keep pull requests scoped');
    expect(content).toContain('- README.md');
  });

  it('discovers useful existing ruleset source candidates', () => {
    fs.mkdirSync(path.join(tempDir, '.codex', 'rules'), { recursive: true });
    fs.writeFileSync(path.join(tempDir, 'AGENTS.md'), '# agents\n', 'utf8');

    const candidates = discoverRulesetCandidates(tempDir);

    expect(candidates).toEqual(expect.arrayContaining([
      'README.md',
      'docs',
      '.codex/rules',
      'AGENTS.md',
    ]));
  });

  it('creates an imported ruleset without a provider under docs/rulesets', async () => {
    getAvailableProvider.mockReturnValue(null);
    const logger = { log: jest.fn() };

    const outPath = await createRulesetFromMode(tempDir, {
      logger,
      mode: 'import-existing',
      goal: 'Keep pull requests scoped',
      title: 'Imported Team Rules',
      pathsCsv: 'README.md, docs',
    });

    const content = fs.readFileSync(outPath, 'utf8');
    expect(path.relative(tempDir, outPath).replace(/\\/g, '/')).toBe('docs/rulesets/imported-team-rules.ruleset.md');
    expect(content).toContain('# RULESET: Imported Team Rules');
    expect(content).toContain('- README.md');
    expect(content).toContain('- docs/guide.md');
    expect(logger.log).toHaveBeenCalledWith(expect.stringContaining('Included context from 2 file(s).'));
  });

  it('creates a local repo ruleset under .grabby/rulesets', async () => {
    getAvailableProvider.mockReturnValue(null);

    const outPath = await createRulesetFromMode(tempDir, {
      logger: { log: () => {} },
      mode: 'create-local',
      goal: 'Define repo-local standards',
      title: 'Local Rules',
      pathsCsv: 'README.md',
    });

    expect(path.relative(tempDir, outPath).replace(/\\/g, '/')).toBe('.grabby/rulesets/local-rules.ruleset.md');
    expect(fs.readFileSync(outPath, 'utf8')).toContain('Define repo-local standards');
  });

  it('uses the provider response and prefixes markdown headers when needed', async () => {
    callLLM.mockResolvedValue('Purpose\n- Generated by AI');
    getAvailableProvider.mockReturnValue('openai');
    const logger = { log: jest.fn() };

    const outPath = await createRulesetFromMode(tempDir, {
      logger,
      mode: 'create-local',
      goal: 'Document guardrails',
      title: 'Provider Rules',
      pathsCsv: 'README.md',
    });

    const content = fs.readFileSync(outPath, 'utf8');
    expect(callLLM).toHaveBeenCalledWith(expect.stringContaining('User goal:\nDocument guardrails'), expect.objectContaining({
      provider: 'openai',
      maxTokens: 1200,
      temperature: 0.3,
    }));
    expect(content.startsWith('# RULESET: Provider Rules')).toBe(true);
    expect(close).not.toHaveBeenCalled();
  });

  it('runs the import wizard interactively', async () => {
    answers = ['1', 'Ingest existing standards', 'Imported Rules', 'README.md, docs'];
    getAvailableProvider.mockReturnValue(null);
    const logger = { log: jest.fn() };

    const outPath = await runRulesetWizard(tempDir, { logger });

    expect(path.relative(tempDir, outPath).replace(/\\/g, '/')).toBe('docs/rulesets/imported-rules.ruleset.md');
    expect(readline.createInterface).toHaveBeenCalled();
    expect(close).toHaveBeenCalled();
    expect(logger.log).toHaveBeenCalledWith(expect.stringContaining('Suggested inputs: README.md, docs'));
  });

  it('runs the local ruleset wizard interactively', async () => {
    answers = ['2', 'Local standards', 'Repo Rules', 'README.md'];
    getAvailableProvider.mockReturnValue(null);

    const outPath = await interactiveCreateRuleset(tempDir, { logger: { log: () => {} } });

    expect(path.relative(tempDir, outPath).replace(/\\/g, '/')).toBe('.grabby/rulesets/repo-rules.ruleset.md');
    expect(close).toHaveBeenCalled();
  });
});
