const fs = require('fs');
const os = require('os');
const path = require('path');
jest.mock('readline', () => ({
  createInterface: jest.fn(),
}));

jest.mock('../lib/ai-complete.cjs', () => ({
  callLLM: jest.fn(),
  getAvailableProvider: jest.fn(),
}));

const readline = require('readline');
const { callLLM, getAvailableProvider } = require('../lib/ai-complete.cjs');
const { interactiveCreateRuleset, resolveInputFiles, summarizeFiles } = require('../lib/ruleset-builder.cjs');

describe('ruleset builder helpers', () => {
  let tempDir;
  let answers;
  let close;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'grabby-ruleset-'));
    fs.mkdirSync(path.join(tempDir, 'docs'), { recursive: true });
    fs.writeFileSync(path.join(tempDir, 'README.md'), '# Hello\n', 'utf8');
    fs.writeFileSync(path.join(tempDir, 'docs', 'guide.md'), 'Guide content', 'utf8');
    fs.writeFileSync(path.join(tempDir, 'docs', 'image.png'), 'not-text', 'utf8');
    close = jest.fn();
    answers = [];
    readline.createInterface.mockImplementation(() => ({
      question: (_prompt, callback) => callback(answers.shift() || ''),
      close,
    }));
    callLLM.mockReset();
    getAvailableProvider.mockReset();
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it('resolves files and ignores non-text files', () => {
    const files = resolveInputFiles(tempDir, ['README.md', 'docs']);
    const rel = files.map((f) => path.relative(tempDir, f).replace(/\\/g, '/')).sort();
    expect(rel).toEqual(['README.md', 'docs/guide.md']);
  });

  it('summarizes file snippets with file markers', () => {
    const files = resolveInputFiles(tempDir, ['README.md']);
    const summary = summarizeFiles(tempDir, files);
    expect(summary).toContain('## File: README.md');
    expect(summary).toContain('# Hello');
  });

  it('clips long summaries and respects the maxChars budget', () => {
    fs.writeFileSync(path.join(tempDir, 'docs', 'long.md'), 'a'.repeat(2600), 'utf8');
    const files = resolveInputFiles(tempDir, ['docs']);
    const summary = summarizeFiles(tempDir, files, 40);
    expect(summary).toContain('## File: docs/guide.md');
    expect(summary).not.toContain('## File: docs/long.md');

    const longOnly = summarizeFiles(tempDir, [path.join(tempDir, 'docs', 'long.md')], 5000);
    expect(longOnly).toContain('...');
  });

  it('creates a fallback ruleset without a provider', async () => {
    getAvailableProvider.mockReturnValue(null);
    const logger = { log: jest.fn() };

    const outPath = await interactiveCreateRuleset(tempDir, {
      logger,
      goal: 'Keep pull requests scoped',
      title: 'Team Rules',
      pathsCsv: 'README.md, docs',
    });

    const content = fs.readFileSync(outPath, 'utf8');
    expect(path.basename(outPath)).toBe('team-rules.ruleset.md');
    expect(content).toContain('# RULESET: Team Rules');
    expect(content).toContain('- Keep pull requests scoped');
    expect(content).toContain('- README.md');
    expect(content).toContain('- docs/guide.md');
    expect(logger.log).toHaveBeenCalledWith(expect.stringContaining('Included context from 2 file(s).'));
    expect(close).toHaveBeenCalled();
  });

  it('uses the provider response and prefixes markdown headers when needed', async () => {
    callLLM.mockResolvedValue('Purpose\n- Generated by AI');
    getAvailableProvider.mockReturnValue('openai');
    const logger = { log: jest.fn() };

    const outPath = await interactiveCreateRuleset(tempDir, {
      logger,
      goal: 'Document guardrails',
      title: 'Provider Rules',
      pathsCsv: 'README.md',
    });

    const content = fs.readFileSync(outPath, 'utf8');
    expect(callLLM).toHaveBeenCalledWith(expect.stringContaining('User goal:\nDocument guardrails'), expect.objectContaining({
      provider: 'openai',
      maxTokens: 1200,
      temperature: 0.3,
    }));
    expect(content.startsWith('# RULESET: Provider Rules')).toBe(true);
    expect(content).toContain('Purpose');
    expect(close).toHaveBeenCalled();
  });

  it('collects interactive answers when options are not prefilled', async () => {
    answers = ['Set coding standards', '   ', 'README.md'];
    getAvailableProvider.mockReturnValue(null);

    const outPath = await interactiveCreateRuleset(tempDir, { logger: { log: () => {} } });

    expect(fs.readFileSync(outPath, 'utf8')).toContain('# RULESET: Custom Ruleset');
    expect(fs.readFileSync(outPath, 'utf8')).toContain('- Set coding standards');
    expect(readline.createInterface).toHaveBeenCalled();
    expect(close).toHaveBeenCalled();
  });
});
