/**
 * CI/CD Integration for Grabby
 * Generates GitHub Actions workflows and pre-merge checks
 */

const fs = require('fs');
const path = require('path');

/**
 * GitHub Actions workflow template
 */
const githubActionsTemplate = `# Grabby Contract Validation
# Auto-generated by: grabby cicd

name: Contract Validation

on:
  pull_request:
    paths:
      - 'contracts/**'
      - '.grabby/**'
  push:
    branches: [main, master]
    paths:
      - 'contracts/**'

jobs:
  validate-contracts:
    name: Validate Contracts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Grabby
        run: npm install -g grabby

      - name: Validate all contracts
        run: |
          echo "Validating contracts..."
          for contract in contracts/*.fc.md; do
            if [ -f "$contract" ]; then
              echo "Checking: $contract"
              grabby validate "$contract"
            fi
          done

      - name: Check for unapproved contracts
        run: |
          unapproved=$(grep -l "Status.*draft" contracts/*.fc.md 2>/dev/null || true)
          if [ -n "$unapproved" ]; then
            echo "::warning::Found draft contracts: $unapproved"
          fi

      - name: Generate metrics
        run: grabby metrics --output json > contract-metrics.json
        continue-on-error: true

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: contract-metrics
          path: contract-metrics.json
          retention-days: 30
        if: always()
`;

/**
 * Pre-commit hook template
 */
const preCommitHookTemplate = `#!/bin/sh
# Grabby pre-commit hook
# Validates contracts before allowing commits

# Find modified contract files
contracts=$(git diff --cached --name-only --diff-filter=ACM | grep '\\.fc\\.md$' || true)

if [ -n "$contracts" ]; then
    echo "Validating modified contracts..."

    for contract in $contracts; do
        if [ -f "$contract" ]; then
            echo "Checking: $contract"
            if ! grabby validate "$contract" 2>/dev/null; then
                echo "ERROR: Contract validation failed: $contract"
                echo "Fix validation errors before committing."
                exit 1
            fi
        fi
    done

    echo "All contracts valid!"
fi

exit 0
`;

/**
 * PR template with contract checklist
 */
const prTemplateContent = `## Description
<!-- Describe your changes -->

## Contract Reference
<!-- Link to the contract for this change -->
- Contract: \`contracts/[name].fc.md\`
- Contract ID: FC-XXXX
- Contract Status: draft/approved/complete

## Checklist

### Contract Compliance
- [ ] Changes are within contract scope
- [ ] Only allowed directories modified
- [ ] No banned dependencies added
- [ ] Tests included as specified

### Quality
- [ ] Contract validation passes (\`grabby validate\`)
- [ ] Lint passes
- [ ] Tests pass with 80%+ coverage

### Security (if applicable)
- [ ] Input validation implemented
- [ ] No secrets in code
- [ ] \`npm audit\` passes
`;

/**
 * Generate GitHub Actions workflow file
 */
function generateGitHubWorkflow(options = {}) {
  const {
    name = 'contract-validation',
    branches = ['main', 'master'],
    nodeVersion = '20',
    strictMode = false,
  } = options;

  let workflow = githubActionsTemplate;

  if (strictMode) {
    workflow = workflow.replace(
      'echo "::warning::Found draft contracts',
      'echo "::error::Found draft contracts'
    );
    workflow = workflow.replace(
      'continue-on-error: true',
      ''
    );
  }

  return workflow;
}

/**
 * Generate all CI/CD files
 */
function generateCICDFiles(projectDir, options = {}) {
  const generated = [];
  const { dryRun = false, force = false } = options;

  // GitHub Actions workflow
  const workflowDir = path.join(projectDir, '.github', 'workflows');
  const workflowFile = path.join(workflowDir, 'contract-validation.yml');

  if (!dryRun) {
    if (!fs.existsSync(workflowDir)) {
      fs.mkdirSync(workflowDir, { recursive: true });
    }

    if (!fs.existsSync(workflowFile) || force) {
      fs.writeFileSync(workflowFile, generateGitHubWorkflow(options));
      generated.push({ type: 'workflow', path: '.github/workflows/contract-validation.yml' });
    }
  } else {
    generated.push({ type: 'workflow', path: '.github/workflows/contract-validation.yml', dryRun: true });
  }

  // PR template
  const prTemplateDir = path.join(projectDir, '.github');
  const prTemplateFile = path.join(prTemplateDir, 'PULL_REQUEST_TEMPLATE.md');

  if (!dryRun) {
    if (!fs.existsSync(prTemplateFile) || force) {
      fs.writeFileSync(prTemplateFile, prTemplateContent);
      generated.push({ type: 'pr-template', path: '.github/PULL_REQUEST_TEMPLATE.md' });
    }
  } else {
    generated.push({ type: 'pr-template', path: '.github/PULL_REQUEST_TEMPLATE.md', dryRun: true });
  }

  // Pre-commit hook (only if .git exists)
  const gitDir = path.join(projectDir, '.git');
  if (fs.existsSync(gitDir)) {
    const hooksDir = path.join(gitDir, 'hooks');
    const preCommitFile = path.join(hooksDir, 'pre-commit');

    if (!dryRun) {
      if (!fs.existsSync(hooksDir)) {
        fs.mkdirSync(hooksDir, { recursive: true });
      }

      if (!fs.existsSync(preCommitFile) || force) {
        fs.writeFileSync(preCommitFile, preCommitHookTemplate);
        try {
          fs.chmodSync(preCommitFile, '755');
        } catch {
          // Windows doesn't support chmod
        }
        generated.push({ type: 'hook', path: '.git/hooks/pre-commit' });
      }
    } else {
      generated.push({ type: 'hook', path: '.git/hooks/pre-commit', dryRun: true });
    }
  }

  return generated;
}

/**
 * Check if CI is properly configured
 */
function checkCICDSetup(projectDir) {
  const checks = [];

  // Check GitHub workflow
  const workflowFile = path.join(projectDir, '.github', 'workflows', 'contract-validation.yml');
  checks.push({
    name: 'GitHub Actions workflow',
    exists: fs.existsSync(workflowFile),
    path: '.github/workflows/contract-validation.yml',
  });

  // Check PR template
  const prTemplate = path.join(projectDir, '.github', 'PULL_REQUEST_TEMPLATE.md');
  checks.push({
    name: 'PR template',
    exists: fs.existsSync(prTemplate),
    path: '.github/PULL_REQUEST_TEMPLATE.md',
  });

  // Check pre-commit hook
  const preCommit = path.join(projectDir, '.git', 'hooks', 'pre-commit');
  checks.push({
    name: 'Pre-commit hook',
    exists: fs.existsSync(preCommit),
    path: '.git/hooks/pre-commit',
  });

  // Check grabby config
  const grabbyConfig = path.join(projectDir, '.grabby', 'config.yaml');
  checks.push({
    name: 'Grabby config',
    exists: fs.existsSync(grabbyConfig),
    path: '.grabby/config.yaml',
  });

  return {
    checks,
    allConfigured: checks.every(c => c.exists),
    missing: checks.filter(c => !c.exists),
  };
}

/**
 * Format CI/CD setup report
 */
function formatSetupReport(setup) {
  const lines = [];

  lines.push('CI/CD Setup Status');
  lines.push('─'.repeat(40));

  for (const check of setup.checks) {
    const icon = check.exists ? '✓' : '✗';
    const color = check.exists ? '\x1b[32m' : '\x1b[31m';
    lines.push(`${color}${icon}\x1b[0m ${check.name}`);
    if (!check.exists) {
      lines.push(`  └─ Missing: ${check.path}`);
    }
  }

  lines.push('');
  if (setup.allConfigured) {
    lines.push('\x1b[32m✓ CI/CD fully configured\x1b[0m');
  } else {
    lines.push(`\x1b[33m! ${setup.missing.length} item(s) not configured\x1b[0m`);
    lines.push('Run: grabby cicd --setup');
  }

  return lines.join('\n');
}

module.exports = {
  generateGitHubWorkflow,
  generateCICDFiles,
  checkCICDSetup,
  formatSetupReport,
  templates: {
    githubActions: githubActionsTemplate,
    preCommitHook: preCommitHookTemplate,
    prTemplate: prTemplateContent,
  },
};
