/**
 * CI/CD Integration for Grabby
 * Generates GitHub Actions workflows and pre-merge checks
 */

const fs = require('fs');
const path = require('path');
const yaml = require('yaml');
const { ensureDir, ensureParentDir } = require('./fs-utils.cjs');

/**
 * GitHub Actions workflow template
 */
const githubActionsTemplate = `# Grabby Contract Validation
# Auto-generated by: grabby cicd

name: Contract Validation

on:
  pull_request:
    paths:
      - 'contracts/**'
      - '.grabby/**'
  push:
    branches: [main, master]
    paths:
      - 'contracts/**'

jobs:
  validate-contracts:
    name: Validate Contracts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Grabby
        run: npm install -g grabby

      - name: Validate all contracts
        run: |
          echo "Validating contracts..."
          for contract in contracts/*.fc.md; do
            if [ -f "$contract" ]; then
              echo "Checking: $contract"
              grabby validate "$contract"
            fi
          done

      - name: Check for unapproved contracts
        run: |
          unapproved=$(grep -l "Status.*draft" contracts/*.fc.md 2>/dev/null || true)
          if [ -n "$unapproved" ]; then
            echo "::warning::Found draft contracts: $unapproved"
          fi

      - name: Generate metrics
        run: grabby metrics --output json > contract-metrics.json
        continue-on-error: true

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: contract-metrics
          path: contract-metrics.json
          retention-days: 30
        if: always()
`;

/**
 * Pre-commit hook template
 */
const preCommitHookTemplate = `#!/bin/sh
# Grabby pre-commit hook
# Validates contracts before allowing commits

# Find modified contract files
contracts=$(git diff --cached --name-only --diff-filter=ACM | grep '\\.fc\\.md$' || true)

if [ -n "$contracts" ]; then
    echo "Validating modified contracts..."

    for contract in $contracts; do
        if [ -f "$contract" ]; then
            echo "Checking: $contract"
            if ! grabby validate "$contract" 2>/dev/null; then
                echo "ERROR: Contract validation failed: $contract"
                echo "Fix validation errors before committing."
                exit 1
            fi
        fi
    done

    echo "All contracts valid!"
fi

exit 0
`;

/**
 * PR template with contract checklist
 */
const prTemplateContent = `## Description
<!-- Describe your changes -->

## Contract Reference
<!-- Link to the contract for this change -->
- Contract: \`contracts/[name].fc.md\`
- Contract ID: FC-XXXX
- Contract Status: draft/approved/complete

## Checklist

### Contract Compliance
- [ ] Changes are within contract scope
- [ ] Only allowed directories modified
- [ ] No banned dependencies added
- [ ] Tests included as specified

### Quality
- [ ] Contract validation passes (\`grabby validate\`)
- [ ] Lint passes
- [ ] Tests pass with 80%+ coverage

### Security (if applicable)
- [ ] Input validation implemented
- [ ] No secrets in code
- [ ] \`npm audit\` passes
`;

function generateGrabbyAutomationConfig(options = {}) {
  const {
    validateCommand = 'grabby validate contracts/<ID>.fc.md',
    planCommand = 'grabby plan contracts/<ID>.fc.md',
    approveCommand = 'grabby approve contracts/<ID>.fc.md',
    executeCommand = 'grabby execute contracts/<ID>.fc.md',
    auditCommand = 'grabby audit contracts/<ID>.fc.md',
    lintCommand = 'npm run lint',
    testCommand = 'npm test -- --runInBand',
  } = options;

  return yaml.stringify({
    version: 1,
    automation: {
      workflow: '.github/workflows/contract-validation.yml',
      prTemplate: '.github/PULL_REQUEST_TEMPLATE.md',
      preCommitHook: '.git/hooks/pre-commit',
    },
    commands: {
      validate: validateCommand,
      plan: planCommand,
      approve: approveCommand,
      execute: executeCommand,
      audit: auditCommand,
      lint: lintCommand,
      test: testCommand,
    },
  });
}

function normalizeAutomationKey(key) {
  const value = String(key || '').trim().toLowerCase();
  if (['workflow', 'github-actions', 'github-actions-workflow'].includes(value)) return 'workflow';
  if (['pr-template', 'pr', 'pull-request-template'].includes(value)) return 'pr-template';
  if (['pre-commit', 'hook', 'precommit'].includes(value)) return 'pre-commit';
  if (['grabby-config', 'config', 'automation-config'].includes(value)) return 'grabby-config';
  return value;
}

function getAutomationTargets(projectDir) {
  return [
    {
      key: 'workflow',
      name: 'GitHub Actions workflow',
      path: '.github/workflows/contract-validation.yml',
      absolutePath: path.join(projectDir, '.github', 'workflows', 'contract-validation.yml'),
      description: 'Validate feature contracts in GitHub Actions.',
      importLabel: 'Import an existing workflow file',
      exists: fs.existsSync(path.join(projectDir, '.github', 'workflows', 'contract-validation.yml')),
    },
    {
      key: 'pr-template',
      name: 'PR template',
      path: '.github/PULL_REQUEST_TEMPLATE.md',
      absolutePath: path.join(projectDir, '.github', 'PULL_REQUEST_TEMPLATE.md'),
      description: 'Add a contract-aware pull request checklist.',
      importLabel: 'Import an existing PR template',
      exists: fs.existsSync(path.join(projectDir, '.github', 'PULL_REQUEST_TEMPLATE.md')),
    },
    {
      key: 'pre-commit',
      name: 'Pre-commit hook',
      path: '.git/hooks/pre-commit',
      absolutePath: path.join(projectDir, '.git', 'hooks', 'pre-commit'),
      description: 'Validate changed contracts before commit.',
      importLabel: 'Import an existing hook script',
      exists: fs.existsSync(path.join(projectDir, '.git', 'hooks', 'pre-commit')),
      requiresGit: true,
    },
    {
      key: 'grabby-config',
      name: 'Grabby config',
      path: '.grabby/config.yaml',
      absolutePath: path.join(projectDir, '.grabby', 'config.yaml'),
      description: 'Store automation-oriented commands and paths for human or agent review.',
      importLabel: 'Import an existing automation config',
      exists: fs.existsSync(path.join(projectDir, '.grabby', 'config.yaml')),
    },
  ];
}

function getAutomationTarget(projectDir, key) {
  const normalized = normalizeAutomationKey(key);
  return getAutomationTargets(projectDir).find((target) => target.key === normalized) || null;
}

function getTemplateContent(key, options = {}) {
  switch (normalizeAutomationKey(key)) {
    case 'workflow':
      return generateGitHubWorkflow(options);
    case 'pr-template':
      return prTemplateContent;
    case 'pre-commit':
      return preCommitHookTemplate;
    case 'grabby-config':
      return generateGrabbyAutomationConfig(options);
    default:
      throw new Error(`Unknown automation target: ${key}`);
  }
}

function writeAutomationFile(projectDir, key, options = {}) {
  const { force = false } = options;
  const target = getAutomationTarget(projectDir, key);
  if (!target) {
    throw new Error(`Unknown automation target: ${key}`);
  }
  if (target.key === 'pre-commit' && !fs.existsSync(path.join(projectDir, '.git'))) {
    throw new Error('Cannot create a pre-commit hook because this repo has no .git directory.');
  }
  if (target.exists && !force) {
    return { created: false, skipped: true, mode: 'generate', target };
  }

  ensureParentDir(target.absolutePath);
  fs.writeFileSync(target.absolutePath, getTemplateContent(target.key, options), 'utf8');
  if (target.key === 'pre-commit') {
    try {
      fs.chmodSync(target.absolutePath, '755');
    } catch {
      // Windows does not require chmod.
    }
  }

  return {
    created: true,
    skipped: false,
    mode: 'generate',
    target: { ...target, exists: true },
  };
}

function importAutomationFile(projectDir, key, importPath, options = {}) {
  const { force = false } = options;
  const target = getAutomationTarget(projectDir, key);
  if (!target) {
    throw new Error(`Unknown automation target: ${key}`);
  }
  if (!importPath) {
    throw new Error(`Import path is required for ${target.name}.`);
  }
  if (target.key === 'pre-commit' && !fs.existsSync(path.join(projectDir, '.git'))) {
    throw new Error('Cannot create a pre-commit hook because this repo has no .git directory.');
  }
  const sourcePath = path.resolve(projectDir, importPath);
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Import path not found: ${importPath}`);
  }
  if (target.exists && !force) {
    return { created: false, skipped: true, mode: 'import', sourcePath, target };
  }

  let content = fs.readFileSync(sourcePath, 'utf8');
  if (target.key === 'grabby-config' && path.extname(sourcePath).toLowerCase() === '.json') {
    content = yaml.stringify(JSON.parse(content));
  }

  ensureParentDir(target.absolutePath);
  fs.writeFileSync(target.absolutePath, content, 'utf8');
  if (target.key === 'pre-commit') {
    try {
      fs.chmodSync(target.absolutePath, '755');
    } catch {
      // Windows does not require chmod.
    }
  }

  return {
    created: true,
    skipped: false,
    mode: 'import',
    sourcePath,
    target: { ...target, exists: true },
  };
}

function configureAutomationFile(projectDir, key, options = {}) {
  if ((options.mode || 'generate') === 'import') {
    return importAutomationFile(projectDir, key, options.importPath, options);
  }
  return writeAutomationFile(projectDir, key, options);
}

/**
 * Generate GitHub Actions workflow file
 */
function generateGitHubWorkflow(options = {}) {
  const {
    name = 'contract-validation',
    branches = ['main', 'master'],
    nodeVersion = '20',
    strictMode = false,
  } = options;

  let workflow = githubActionsTemplate;

  if (strictMode) {
    workflow = workflow.replace(
      'echo "::warning::Found draft contracts',
      'echo "::error::Found draft contracts'
    );
    workflow = workflow.replace(
      'continue-on-error: true',
      ''
    );
  }

  return workflow;
}

/**
 * Generate all CI/CD files
 */
function generateCICDFiles(projectDir, options = {}) {
  const generated = [];
  const { dryRun = false, force = false } = options;

  getAutomationTargets(projectDir).forEach((target) => {
    if (target.requiresGit && !fs.existsSync(path.join(projectDir, '.git'))) {
      return;
    }
    if (dryRun) {
      generated.push({ type: target.key, path: target.path, dryRun: true });
      return;
    }
    const result = writeAutomationFile(projectDir, target.key, { ...options, force });
    if (result.created) {
      generated.push({ type: target.key, path: target.path });
    }
  });

  return generated;
}

/**
 * Check if CI is properly configured
 */
function checkCICDSetup(projectDir) {
  const checks = getAutomationTargets(projectDir).map((target) => ({
    key: target.key,
    name: target.name,
    exists: target.exists,
    path: target.path,
    description: target.description,
  }));

  return {
    checks,
    allConfigured: checks.every(c => c.exists),
    missing: checks.filter(c => !c.exists),
  };
}

/**
 * Format CI/CD setup report
 */
function formatSetupReport(setup) {
  const lines = [];

  lines.push('CI/CD Setup Status');
  lines.push('─'.repeat(40));

  for (const check of setup.checks) {
    const icon = check.exists ? '✓' : '✗';
    const color = check.exists ? '\x1b[32m' : '\x1b[31m';
    lines.push(`${color}${icon}\x1b[0m ${check.name}`);
    if (!check.exists) {
      lines.push(`  └─ Missing: ${check.path}`);
    }
  }

  lines.push('');
  if (setup.allConfigured) {
    lines.push('\x1b[32m✓ CI/CD fully configured\x1b[0m');
  } else {
    lines.push(`\x1b[33m! ${setup.missing.length} item(s) not configured\x1b[0m`);
    lines.push('Run: grabby cicd --setup');
  }

  return lines.join('\n');
}

function formatSetupReportAscii(setup) {
  const lines = [];

  lines.push('CI/CD Setup Status');
  lines.push('-'.repeat(40));

  for (const check of setup.checks) {
    const icon = check.exists ? '[x]' : '[ ]';
    const color = check.exists ? '\x1b[32m' : '\x1b[31m';
    lines.push(`${color}${icon}\x1b[0m ${check.name}`);
    if (!check.exists) {
      lines.push(`  Missing: ${check.path}`);
    }
  }

  lines.push('');
  if (setup.allConfigured) {
    lines.push('\x1b[32m[x] CI/CD fully configured\x1b[0m');
  } else {
    lines.push(`\x1b[33m! ${setup.missing.length} item(s) not configured\x1b[0m`);
    lines.push('Run: grabby cicd --setup or use the Automation menu wizard');
  }

  return lines.join('\n');
}

module.exports = {
  generateGitHubWorkflow,
  generateGrabbyAutomationConfig,
  generateCICDFiles,
  getAutomationTargets,
  getAutomationTarget,
  writeAutomationFile,
  importAutomationFile,
  configureAutomationFile,
  checkCICDSetup,
  formatSetupReport: formatSetupReportAscii,
  templates: {
    githubActions: githubActionsTemplate,
    preCommitHook: preCommitHookTemplate,
    prTemplate: prTemplateContent,
  },
};
